--Creation of the Database--
CREATE DATABASE customer_behaviour ;

--Run the Database--
USE customer_behavior
GO

SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

--Show the data in the Databas
SELECT * 
FROM customer_data


--Q1. What is the total revenue generated by Male and Female cutomers?--
SELECT gender, SUM(purchase_amount) as revenue
from customer_data
group by gender


--Q2. Which custmer used a discount but still spent more than the avaerage purchase amount?--
SELECT customer_id, purchase_amount
FROM customer_data
where discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer_data);

--Q3. Which are the top 5 products with the highest averege review ratting?--
SELECT TOP 5 item_purchased, AVG(review_rating) as "Average product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc

--Q4. Compare the average purchase amount between standard and express shopping?--

SELECT shipping_type,
AVG(purchase_amount)
FROM customer_data
WHERE  shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more?Compare averge spend and the total revenue between subscribers and non-subscribers--
SELECT subscription_status ,
COUNT(customer_id)as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchase with discounts applied?--
SELECT TOP 5 item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END) / COUNT(*) * 100,2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. What is the revenue contribution of each age group ?--
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;